function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Requests.do_stream_request, (Array{Any, 1}, URIParser.URI, ASCIIString,))
    precompile(Requests.prepare_multipart_request!, (HttpCommon.Request, Array{Requests.FileParam, 1},))
    precompile(Requests.parse_cookies!, (HttpCommon.Response, ASCIIString,))
    precompile(Requests.send_multipart, (Requests.ResponseStream{Base.TCPSocket}, Requests.MultipartSettings, Array{Requests.FileParam, 1},))
    precompile(Requests.format_query_str, (Array{Any, 1}, Base.Dict{ASCIIString, Any},))
    precompile(Requests.open_stream, (HttpCommon.Request, MbedTLS.SSLConfig, Float64,))
    precompile(Requests.format_query_str, (Array{Any, 1}, Base.Dict{Symbol, Int64},))
    precompile(Requests.format_query_str, (Array{Any, 1}, Base.Dict{ASCIIString, ASCIIString},))
    precompile(Requests.call, (Type{Requests.ResponseStream}, HttpCommon.Response, MbedTLS.SSLContext,))
    precompile(Requests.format_query_str, (Array{Any, 1}, Base.Dict{Any, Any},))
    precompile(Requests.process_response, (Requests.ResponseStream{MbedTLS.SSLContext},))
    precompile(Requests.call, (Type{Requests.ResponseStream}, HttpCommon.Response, Base.TCPSocket,))
    precompile(Requests.get_redirect_uri, (Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.get_redirect_uri, (Requests.ResponseStream{MbedTLS.SSLContext},))
    precompile(Requests.default_request, (ASCIIString, ASCIIString, ASCIIString, ASCIIString, Base.Dict{ASCIIString, ASCIIString},))
    precompile(Requests.default_request, (ASCIIString, ASCIIString, ASCIIString, ASCIIString, Base.Dict{AbstractString, AbstractString},))
    precompile(Requests.default_request, (ASCIIString, ASCIIString, ASCIIString, UTF8String, Base.Dict{ASCIIString, ASCIIString},))
    precompile(Requests.put, (Array{Any, 1}, ASCIIString,))
    precompile(Requests.post_streaming, (Array{Any, 1}, URIParser.URI,))
    precompile(Requests.cookie_request_header, (Base.Dict{UTF8String, HttpCommon.Cookie},))
    precompile(Requests.process_response, (Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.post_streaming, (Array{Any, 1}, ASCIIString,))
    precompile(Requests.options, (Array{Any, 1}, URIParser.URI,))
    precompile(Requests.delete, (Array{Any, 1}, URIParser.URI,))
    precompile(Requests.get_streaming, (Array{Any, 1}, URIParser.URI,))
    precompile(Requests.on_header_value, (Ptr{HttpParser.Parser}, Ptr{Int8}, UInt64,))
    precompile(Requests.get, (Array{Any, 1}, URIParser.URI,))
    precompile(Requests.options, (Array{Any, 1}, ASCIIString,))
    precompile(Requests.put, (Array{Any, 1}, URIParser.URI,))
    precompile(Requests.send_headers, (Requests.ResponseStream{MbedTLS.SSLContext},))
    precompile(Requests.do_request, (Array{Any, 1}, URIParser.URI, ASCIIString,))
    precompile(Requests.delete, (Array{Any, 1}, ASCIIString,))
    precompile(Requests.get, (Array{Any, 1}, ASCIIString,))
    precompile(Requests.post, (Array{Any, 1}, URIParser.URI,))
    precompile(Requests.post, (Array{Any, 1}, ASCIIString,))
    precompile(Requests.on_header_field, (Ptr{HttpParser.Parser}, Ptr{Int8}, UInt64,))
    precompile(Requests.send_headers, (Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.on_headers_complete, (Ptr{HttpParser.Parser},))
    precompile(Requests.get_streaming, (Array{Any, 1}, ASCIIString,))
    precompile(Requests.write_part_header, (Requests.ResponseStream{Base.TCPSocket}, Requests.FileParam, ASCIIString,))
    precompile(Requests.write_file, (Requests.ResponseStream{Base.TCPSocket}, Base.IOStream, Int64, Bool,))
    precompile(Requests.call, (Type{Requests.ResponseParser}, Requests.ResponseStream{MbedTLS.SSLContext},))
    precompile(Requests.write_part_header, (Requests.ChunkedStream, Requests.FileParam, ASCIIString,))
    precompile(Requests.requestfor, (HttpCommon.Response,))
    precompile(Requests.default_request, (URIParser.URI, Base.Dict{ASCIIString, ASCIIString}, UTF8String, ASCIIString,))
    precompile(Requests.__init_parsing__, ())
    precompile(Requests.default_request, (URIParser.URI, Base.Dict{ASCIIString, ASCIIString}, ASCIIString, ASCIIString,))
    precompile(Requests.write_file, (Requests.ResponseStream{Base.TCPSocket}, Base.AbstractIOBuffer{Array{UInt8, 1}}, Int64, Bool,))
    precompile(Requests.default_request, (URIParser.URI, Base.Dict{AbstractString, AbstractString}, ASCIIString, ASCIIString,))
    precompile(Requests.call, (Type{Requests.ResponseParser}, Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.write_file, (Requests.ResponseStream{Base.TCPSocket}, UTF8String, Int64, Bool,))
    precompile(Requests.readbytes!, (Requests.ResponseStream{Base.TCPSocket}, Array{UInt8, 1}, Int64,))
    precompile(Requests.on_body, (Ptr{HttpParser.Parser}, Ptr{Int8}, UInt64,))
    precompile(Requests.on_url, (Ptr{HttpParser.Parser}, Ptr{Int8}, UInt64,))
    precompile(Requests.partheadersize, (Requests.FileParam, Int64, ASCIIString,))
    precompile(Requests.readavailable, (Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.get_default_tls_config, (Bool,))
    precompile(Requests.on_message_begin, (Ptr{HttpParser.Parser},))
    precompile(Requests.do_stream_request, (URIParser.URI, ASCIIString,))
    precompile(Requests.write_chunked, (Requests.ResponseStream{Base.TCPSocket}, ASCIIString,))
    precompile(Requests.on_message_complete, (Ptr{HttpParser.Parser},))
    precompile(Requests.readbytes, (Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.eof, (Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.readbytes, (Requests.ResponseStream{MbedTLS.SSLContext},))
    precompile(Requests.on_status_complete, (Ptr{HttpParser.Parser},))
    precompile(Requests.wait, (Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.write, (Requests.ResponseStream{MbedTLS.SSLContext}, Array{UInt8, 1},))
    precompile(Requests.wait, (Requests.ResponseStream{MbedTLS.SSLContext},))
    precompile(Requests.call, (Type{Requests.FileParam}, Base.IOStream, ASCIIString, ASCIIString, ASCIIString, Bool,))
    precompile(Requests.text, (HttpCommon.Response,))
    precompile(Requests.write, (Requests.ResponseStream{Base.TCPSocket}, Array{UInt8, 1},))
    precompile(Requests.call, (Type{Requests.FileParam}, UTF8String, ASCIIString, ASCIIString, ASCIIString,))
    precompile(Requests.call, (Type{Requests.FileParam}, Base.AbstractIOBuffer{Array{UInt8, 1}}, ASCIIString, ASCIIString, ASCIIString,))
    precompile(Requests.datasize, (Base.IOStream,))
    precompile(Requests.datasize, (Base.AbstractIOBuffer{Array{UInt8, 1}},))
    precompile(Requests.delete, (ASCIIString,))
    precompile(Requests.call, (Type{Requests.MultipartSettings}, Array{Int64, 1}, ASCIIString, Bool,))
    precompile(Requests.options, (ASCIIString,))
    precompile(Requests.close, (Requests.ResponseStream{Base.TCPSocket},))
    precompile(Requests.close, (Requests.ResponseStream{MbedTLS.SSLContext},))
    precompile(Requests.put, (ASCIIString,))
    precompile(Requests.post, (ASCIIString,))
    precompile(Requests.timeout_in_sec, (Base.Dates.Millisecond,))
    precompile(Requests.datasize, (UTF8String,))
    precompile(Requests.json, (HttpCommon.Response,))
    precompile(Requests.get, (ASCIIString,))
    precompile(Requests.statuscode, (HttpCommon.Response,))
    precompile(Requests.__init_streaming__, ())
    precompile(Requests.history, (HttpCommon.Response,))
    precompile(Requests.__init__, ())
end
