module WebSockets

using Base64, Random, AwsHTTP, AwsIO

import ..Headers, ..Header, ..Request, ..Response, ..Message, ..Stream
import ..setinputstream!, ..getresponse, ..getheader, ..hasheader, ..header
import ..addheader, ..setheader, ..removeheader
import ..Future, ..parseuri, ..with_redirect, ..with_request, ..getclient
import ..ClientSettings, ..scheme, ..host, ..getport, ..userinfo, ..resource
import ..Client, ..CookieJar, ..COOKIEJAR, ..with_connection, .._open_stream
import ..aws_throw_error, ..aws_error, ..AWSError
import .._h1_flush_outgoing!, ..iswss, ..makeuri, ..HTTP, ..mkreqheaders
import ..startread, ..closeread, ..startwrite, ..closewrite

export WebSocket, send, receive, ping, pong

# ─── Types ───

@enum OpCode::UInt8 CONTINUATION=0x00 TEXT=0x01 BINARY=0x02 CLOSE=0x08 PING=0x09 PONG=0x0A

const DEFAULT_MAX_FRAG = 1024

struct CloseFrameBody
    code::Int
    reason::String
end

struct WebSocketError <: Exception
    message::CloseFrameBody
end

isok(e::WebSocketError) = e.message.code in (1000, 1001, 1005)
isok(::Any) = false

function isupgrade(r::Message)
    ((r isa Request && r.method == "GET") ||
     (r isa Response && r.status == 101)) &&
    (hasheader(r, "Connection", "upgrade") ||
     hasheader(r, "Connection", "keep-alive, upgrade")) &&
    hasheader(r, "Upgrade", "websocket")
end

isupgrade(s::Stream) = isupgrade(s.request)

Base.@deprecate is_upgrade isupgrade

# ─── WsChannelHandler ───
# Bridges the AwsIO channel pipeline with the AwsHTTP WebSocket codec.
# Installed into the H1Connection's channel slot after HTTP 101 upgrade.

mutable struct WsChannelHandler <: AwsIO.AbstractChannelHandler
    slot::Union{AwsIO.ChannelSlot, Nothing}
    aws_ws::Any  # AwsHTTP.WebSocket
    wslock::ReentrantLock  # protects outgoing_frames access
    ws::Any
end

WsChannelHandler(aws_ws, ws) = WsChannelHandler(nothing, aws_ws, ReentrantLock(), ws)

function AwsIO.setchannelslot!(handler::WsChannelHandler, slot::AwsIO.ChannelSlot)::Nothing
    handler.slot = slot
    return nothing
end

function AwsIO.handler_process_read_message(handler::WsChannelHandler, slot::AwsIO.ChannelSlot, message::AwsIO.IoMessage)::Union{Nothing, AwsIO.ErrorResult}
    data = AwsIO.byte_buffer_as_vector(message.message_data)
    isempty(data) && return nothing
    @lock handler.wslock begin
        status, _ = AwsHTTP.ws_on_incoming_data!(handler.aws_ws, data)
        if status != AwsHTTP.OP_SUCCESS
            ws = handler.ws
            if ws !== nothing && !ws.readclosed
                close_body = status == AwsHTTP.ERROR_HTTP_WEBSOCKET_PROTOCOL_ERROR ?
                    CloseFrameBody(1002, "WebSocket protocol error") :
                    CloseFrameBody(1011, "WebSocket error")
                _queue_close!(ws, close_body)
                errormonitor(Threads.@spawn close(ws, close_body))
            end
            return AwsIO.ErrorResult(status)
        end
        # Flush auto-responses (PONG, CLOSE echo) generated by ws_on_incoming_data!
        _ws_channel_flush!(handler)
    end
    return nothing
end

function AwsIO.handler_process_write_message(handler::WsChannelHandler, slot::AwsIO.ChannelSlot, message::AwsIO.IoMessage)::Union{Nothing, AwsIO.ErrorResult}
    # Pass through to lower pipeline (socket)
    return AwsIO.channel_slot_send_message(slot, message, AwsIO.ChannelDirection.WRITE)
end

function AwsIO.handler_increment_read_window(handler::WsChannelHandler, slot::AwsIO.ChannelSlot, size::Csize_t)::Union{Nothing, AwsIO.ErrorResult}
    return AwsIO.channel_slot_increment_read_window!(slot, size)
end

function AwsIO.handler_shutdown(
        handler::WsChannelHandler,
        slot::AwsIO.ChannelSlot,
        direction::AwsIO.ChannelDirection.T,
        error_code::Int,
        free_scarce_resources_immediately::Bool,
    )::Union{Nothing, AwsIO.ErrorResult}
    ws = handler.ws
    if ws !== nothing && !ws.readclosed
        _queue_close!(ws, CloseFrameBody(1006, ""))
    end
    AwsIO.channel_slot_on_handler_shutdown_complete!(slot, direction, error_code, free_scarce_resources_immediately)
    return nothing
end

AwsIO.handler_initial_window_size(::WsChannelHandler)::Csize_t = Csize_t(typemax(UInt64))
AwsIO.handler_message_overhead(::WsChannelHandler)::Csize_t = Csize_t(0)

# Collect outgoing frames from the AwsHTTP WebSocket codec and send them
# through the channel pipeline. Caller MUST hold handler.wslock.
function _ws_channel_flush!(handler::WsChannelHandler)
    outdata = AwsHTTP.ws_get_outgoing_data!(handler.aws_ws)
    isempty(outdata) && return
    slot = handler.slot
    slot === nothing && return
    channel = slot.channel
    channel === nothing && return
    msg = AwsIO.IoMessage(length(outdata))
    buf = msg.message_data
    @inbounds for i in 1:length(outdata)
        buf.mem[i] = outdata[i]
    end
    buf.len = Csize_t(length(outdata))
    if AwsIO.channel_thread_is_callers_thread(channel)
        AwsIO.channel_slot_send_message(slot, msg, AwsIO.ChannelDirection.WRITE)
        return
    end
    task = AwsIO.ChannelTask((task, ctx, status) -> begin
        status == AwsIO.TaskStatus.RUN_READY || return nothing
        AwsIO.channel_slot_send_message(ctx.slot, ctx.msg, AwsIO.ChannelDirection.WRITE)
        return nothing
    end, (slot=slot, msg=msg), "http_ws_flush")
    AwsIO.channel_schedule_task_now!(channel, task)
    return
end

# ─── WebSocket struct ───

mutable struct WebSocket
    id::String
    host::String
    path::String
    maxframesize::Int
    maxfragmentation::Int
    is_client::Bool
    readchannel::Channel{Union{String, Vector{UInt8}, WebSocketError}}
    readclosed::Bool
    writeclosed::Bool
    closelock::ReentrantLock
    sendlock::ReentrantLock
    handshake_request::Union{Nothing, Request}
    handshake_response::Union{Nothing, Response}
    # AwsHTTP WebSocket codec + channel handler
    aws_ws::Any    # AwsHTTP.WebSocket
    handler::Any   # WsChannelHandler
    # Fragment tracking
    incoming_opcode::UInt8
    incoming_fin::Bool
    incoming_payload::Vector{UInt8}
    fragment_opcode::Union{Nothing, UInt8}
    fragment_payload::Vector{UInt8}
    fragment_count::Int
    drop_incoming::Bool
    closebody::Union{Nothing, CloseFrameBody}

    WebSocket(host::AbstractString, path::AbstractString; maxframesize::Integer=typemax(Int), maxfragmentation::Integer=DEFAULT_MAX_FRAG, is_client::Bool=true) = new(
        string(rand(UInt32); base=58),
        String(host),
        String(path),
        Int(maxframesize),
        Int(maxfragmentation),
        is_client,
        Channel{Union{String, Vector{UInt8}, WebSocketError}}(Inf),
        false,
        false,
        ReentrantLock(),
        ReentrantLock(),
        nothing,
        nothing,
        nothing, # aws_ws
        nothing, # handler
        0x00,
        false,
        UInt8[],
        nothing,
        UInt8[],
        0,
        false,
        nothing,
    )
end

getresponse(ws::WebSocket) = ws.handshake_response

# ─── Internal helpers ───

function _queue_close!(ws::WebSocket, body::CloseFrameBody)
    ws.closebody = body
    ws.readclosed = true
    if isopen(ws.readchannel)
        try
            put!(ws.readchannel, WebSocketError(body))
        catch
        end
        Base.close(ws.readchannel)
    end
    return
end

function _close_channel!(ws::WebSocket)
    isopen(ws.readchannel) && Base.close(ws.readchannel)
    return
end

function _shutdown_ws_channel!(handler::WsChannelHandler)
    slot = handler.slot
    slot === nothing && return
    channel = slot.channel
    channel === nothing && return
    AwsIO.channel_shutdown!(channel; shutdown_immediately=true)
    return
end

function _enqueue_message!(ws::WebSocket, msg)
    if isopen(ws.readchannel)
        try
            put!(ws.readchannel, msg)
        catch
        end
    end
    return
end

function _valid_close_status(code::Int)::Bool
    code < 0 && return false
    code > typemax(UInt16) && return false
    return AwsHTTP.ws_is_valid_close_status(UInt16(code))
end

function _queue_protocol_error!(ws::WebSocket, reason::String)
    close_body = CloseFrameBody(1002, reason)
    _queue_close!(ws, close_body)
    errormonitor(Threads.@spawn close(ws, close_body))
    return
end

function _queue_invalid_payload!(ws::WebSocket, reason::String)
    close_body = CloseFrameBody(1007, reason)
    _queue_close!(ws, close_body)
    errormonitor(Threads.@spawn close(ws, close_body))
    return
end

function close_payload(body::CloseFrameBody)
    reason_bytes = collect(codeunits(body.reason))
    payload = Vector{UInt8}(undef, 2 + length(reason_bytes))
    payload[1] = UInt8((body.code >> 8) & 0xff)
    payload[2] = UInt8(body.code & 0xff)
    if !isempty(reason_bytes)
        copyto!(payload, 3, reason_bytes, 1, length(reason_bytes))
    end
    return payload
end

isbinary(x) = x isa AbstractVector{UInt8}
istext(x) = x isa AbstractString
opcode(x) = isbinary(x) ? BINARY : TEXT

_to_bytes(x::AbstractVector{UInt8}) = x
_to_bytes(x) = Vector{UInt8}(codeunits(string(x)))

# ─── AwsHTTP WebSocket callback builders ───
# These create the closure callbacks passed to AwsHTTP.ws_new().
# Each closure captures the HTTP.WebSocket and manipulates it directly.

function _on_incoming_frame_begin(ws::WebSocket)
    return (aws_ws, frame_info, user_data) -> begin
        ws.incoming_opcode = frame_info.opcode
        ws.incoming_fin = frame_info.fin
        empty!(ws.incoming_payload)
        ws.drop_incoming = false
        if frame_info.payload_length > ws.maxframesize
            close_body = CloseFrameBody(1009, "frame too large")
            _queue_close!(ws, close_body)
            errormonitor(Threads.@spawn close(ws, close_body))
            ws.drop_incoming = true
        end
        frame_info.payload_length > 0 && sizehint!(ws.incoming_payload, Int(frame_info.payload_length))
        return true
    end
end

function _on_incoming_frame_payload(ws::WebSocket)
    return (aws_ws, frame_info, data, user_data) -> begin
        ws.drop_incoming && return true
        try
            n = length(data)
            n == 0 && return true
            append!(ws.incoming_payload, data)
        catch e
            @error "$(ws.id): incoming frame payload error" exception=(e, catch_backtrace())
        end
        return true
    end
end

function _on_incoming_frame_complete(ws::WebSocket)
    return (aws_ws, frame_info, error_code, user_data) -> begin
        if error_code != 0
            @error "$(ws.id): incoming frame complete error" error_code
            close_body = CloseFrameBody(1006, "")
            _queue_close!(ws, close_body)
            errormonitor(Threads.@spawn close(ws, close_body))
            return true
        end
        if ws.drop_incoming
            ws.drop_incoming = false
            return true
        end
        op = frame_info.opcode
        fin = frame_info.fin
        payload = ws.incoming_payload
        # PING/PONG: AwsHTTP handles auto-PONG, nothing to do here
        if op == UInt8(PING) || op == UInt8(PONG)
            return true
        end
        # CLOSE: AwsHTTP auto-echoes, we just track state
        if op == UInt8(CLOSE)
            body = payload
            if length(body) == 1
                _queue_protocol_error!(ws, "invalid close payload length")
                return true
            end
            close_body = if length(body) >= 2
                code = (Int(body[1]) << 8) | Int(body[2])
                _valid_close_status(code) || (_queue_protocol_error!(ws, "invalid close status code"); return true)
                reason_bytes = length(body) > 2 ? body[3:end] : UInt8[]
                if !isempty(reason_bytes) && !isvalid(String, reason_bytes)
                    _queue_invalid_payload!(ws, "invalid close reason")
                    return true
                end
                reason = length(body) > 2 ? String(copy(reason_bytes)) : ""
                CloseFrameBody(code, reason)
            else
                CloseFrameBody(1005, "")
            end
            # AwsHTTP will echo the CLOSE and set close_sent=true, is_open=false
            ws.writeclosed = true
            _queue_close!(ws, close_body)
            return true
        end
        # Data frames: TEXT, BINARY, CONTINUATION
        if op == UInt8(CONTINUATION)
            if ws.fragment_opcode === nothing
                _queue_protocol_error!(ws, "unexpected continuation")
                return true
            end
            ws.fragment_count += 1
            if ws.fragment_count > ws.maxfragmentation
                close_body = CloseFrameBody(1009, "message too large")
                _queue_close!(ws, close_body)
                errormonitor(Threads.@spawn close(ws, close_body))
                return true
            end
            append!(ws.fragment_payload, payload)
            if fin
                msg_opcode = ws.fragment_opcode
                data = ws.fragment_payload
                ws.fragment_opcode = nothing
                ws.fragment_payload = UInt8[]
                ws.fragment_count = 0
                if msg_opcode == UInt8(TEXT)
                    if !isvalid(String, data)
                        _queue_invalid_payload!(ws, "invalid UTF-8")
                        return true
                    end
                    _enqueue_message!(ws, String(copy(data)))
                else
                    _enqueue_message!(ws, copy(data))
                end
            end
            return true
        end
        if op == UInt8(TEXT) || op == UInt8(BINARY)
            if ws.fragment_opcode !== nothing
                _queue_protocol_error!(ws, "unexpected new data frame")
                return true
            end
            if fin
                if op == UInt8(TEXT)
                    if !isvalid(String, payload)
                        _queue_invalid_payload!(ws, "invalid UTF-8")
                        return true
                    end
                    _enqueue_message!(ws, String(copy(payload)))
                else
                    _enqueue_message!(ws, copy(payload))
                end
                ws.fragment_count = 0
            else
                ws.fragment_opcode = op
                ws.fragment_payload = copy(payload)
                ws.fragment_count = 1
                if ws.fragment_count > ws.maxfragmentation
                    close_body = CloseFrameBody(1009, "message too large")
                    _queue_close!(ws, close_body)
                    errormonitor(Threads.@spawn close(ws, close_body))
                    return true
                end
            end
        end
        return true
    end
end

# Create an AwsHTTP WebSocket and WsChannelHandler, then install
# the handler into the H1Connection's channel slot.
function _create_ws_handler!(ws::WebSocket, slot::AwsIO.ChannelSlot, is_client::Bool)
    aws_ws = AwsHTTP.ws_new(;
        is_client=is_client,
        on_incoming_frame_begin=_on_incoming_frame_begin(ws),
        on_incoming_frame_payload=_on_incoming_frame_payload(ws),
        on_incoming_frame_complete=_on_incoming_frame_complete(ws),
    )
    handler = WsChannelHandler(aws_ws, ws)
    ws.aws_ws = aws_ws
    ws.handler = handler
    AwsIO.channel_slot_set_handler!(slot, handler)
    return
end

# ─── writeframe ───

function writeframe(ws::WebSocket, fin::Bool, opcode::OpCode, payload::AbstractVector{UInt8})
    handler = ws.handler
    handler === nothing && throw(WebSocketError(CloseFrameBody(1006, "WebSocket not connected")))
    @lock handler.wslock begin
        ret = AwsHTTP.ws_send_frame!(handler.aws_ws, UInt8(opcode), payload; fin=fin)
        ret != AwsHTTP.OP_SUCCESS && throw(AWSError("ws_send_frame! failed"))
        _ws_channel_flush!(handler)
    end
    return length(payload)
end

# ─── Public API ───

"""
    send(ws::WebSocket, msg)

Send a message on a websocket connection. If `msg` is an `AbstractString`,
a TEXT websocket message will be sent; if `msg` is an `AbstractVector{UInt8}`,
a BINARY websocket message will be sent. Otherwise, `msg` should be an iterable
of either `AbstractString` or `AbstractVector{UInt8}`, and a fragmented message
will be sent, one frame for each iterated element.

Control frames can be sent by calling `ping(ws[, data])`, `pong(ws[, data])`,
or `close(ws[, body::WebSockets.CloseFrameBody])`. Calling `close` will initiate
the close sequence and close the underlying connection.
"""
function send(ws::WebSocket, x)
    @lock ws.sendlock begin
        @assert !ws.writeclosed "WebSocket is closed"
        if !isbinary(x) && !istext(x)
            # iterable of binary or text → fragmented message
            first = true
            n = 0
            state = iterate(x)
            if state === nothing
                x = ""
                @goto write_single_frame
            end
            item, st = state
            nextstate = iterate(x, st)
            while true
                n += writeframe(ws, nextstate === nothing, first ? opcode(item) : CONTINUATION, _to_bytes(item))
                first = false
                nextstate === nothing && break
                item, st = nextstate
                nextstate = iterate(x, st)
            end
            return n
        else
@label write_single_frame
            return writeframe(ws, true, opcode(x), _to_bytes(x))
        end
    end
end

"""
    ping(ws, data=[])

Send a PING control frame on a websocket connection. `data` is an optional
body to send with the message. PONG messages are automatically responded
to when a PING message is received by a websocket connection.
"""
function ping(ws::WebSocket, data=UInt8[])
    @lock ws.sendlock begin
        @assert !ws.writeclosed "WebSocket is closed"
        return writeframe(ws, true, PING, _to_bytes(data))
    end
end

"""
    pong(ws, data=[])

Send a PONG control frame on a websocket connection. `data` is an optional
body to send with the message. Note that PING messages are automatically
responded to internally by the websocket connection with a corresponding
PONG message, but in certain cases, a unidirectional PONG message can be
used as a one-way heartbeat.
"""
function pong(ws::WebSocket, data=UInt8[])
    @lock ws.sendlock begin
        @assert !ws.writeclosed "WebSocket is closed"
        return writeframe(ws, true, PONG, _to_bytes(data))
    end
end

"""
    receive(ws::WebSocket) -> Union{String, Vector{UInt8}}

Receive a message from a websocket connection. Returns a `String` if
the message was TEXT, or a `Vector{UInt8}` if the message was BINARY.
If control frames (ping or pong) are received, they are handled
automatically and a non-control message is waited for. If a CLOSE
message is received, it is responded to and a `WebSocketError` is thrown
with the `WebSockets.CloseFrameBody` as the error value. This error can
be checked with `WebSockets.isok(err)` to see if the closing was "normal"
or if an actual error occurred. For fragmented messages, the incoming
frames will continue to be read until the final fragment is received.
The bodies of each fragment are concatenated into the final message
returned by `receive`. Note that `WebSocket` objects can be iterated,
where each iteration yields a message until the connection is closed.
"""
function receive(ws::WebSocket)
    if ws.readclosed || !isopen(ws.readchannel)
        close_body = ws.closebody === nothing ? CloseFrameBody(1006, "") : ws.closebody
        throw(WebSocketError(close_body))
    end
    msg = take!(ws.readchannel)
    if msg isa WebSocketError
        throw(msg)
    end
    return msg
end

"""
    iterate(ws)

Continuously call `receive(ws)` on a `WebSocket` connection, with
each iteration yielding a message until the connection is closed.
E.g.
```julia
for msg in ws
    # do something with msg
end
```
"""
function Base.iterate(ws::WebSocket, st=nothing)
    isclosed(ws) && return nothing
    try
        return receive(ws), nothing
    catch e
        isok(e) && return nothing
        rethrow(e)
    end
end

"""
    WebSockets.isclosed(ws) -> Bool

Check whether a `WebSocket` has sent and received CLOSE frames
"""
isclosed(ws::WebSocket) = ws.readclosed && ws.writeclosed

function Base.close(ws::WebSocket, body::Union{Nothing, CloseFrameBody}=nothing)
    handler = ws.handler
    @lock ws.closelock begin
        if ws.writeclosed
            _close_channel!(ws)
            return
        end
        ws.writeclosed = true
        if handler !== nothing
            close_body = body === nothing ? CloseFrameBody(1000, "") : body
            code = UInt16(close_body.code)
            reason = Vector{UInt8}(codeunits(close_body.reason))
            @lock handler.wslock begin
                try
                    AwsHTTP.ws_close!(handler.aws_ws; status_code=code, reason=reason)
                    _ws_channel_flush!(handler)
                catch
                    # ignore errors while closing
                end
            end
        end
    end
    if !ws.readclosed
        deadline = time() + 5.0
        while time() < deadline
            ws.readclosed && break
            sleep(0.05)
        end
        ws.readclosed = true
    end
    if !ws.is_client && handler !== nothing
        _shutdown_ws_channel!(handler)
    end
    _close_channel!(ws)
    return
end

@noinline handshakeerror() = throw(WebSocketError(CloseFrameBody(1002, "Websocket handshake failed")))

# ─── Client-side open ───

function open(f::Function, url;
    suppress_close_error::Bool=false,
    headers=[],
    maxframesize::Integer=typemax(Int),
    maxfragmentation::Integer=DEFAULT_MAX_FRAG,
    username=nothing,
    password=nothing,
    bearer=nothing,
    query=nothing,
    client::Union{Nothing, Client}=nothing,
    # redirect options
    redirect=true,
    redirect_limit=3,
    redirect_method=nothing,
    forwardheaders=true,
    # cookie options
    cookies=true,
    cookiejar::CookieJar=COOKIEJAR,
    modifier=nothing,
    verbose=0,
    # client keywords
    kw...
    )
    key = base64encode(rand(Random.RandomDevice(), UInt8, 16))
    expected_accept = AwsHTTP.ws_compute_accept_key(key)
    uri = parseuri(url, query)
    # add required websocket headers
    headers = collect(headers)
    append!(headers, [
        "upgrade" => "websocket",
        "connection" => "upgrade",
        "sec-websocket-key" => key,
        "sec-websocket-version" => "13"
    ])
    ws = with_redirect("GET", uri, headers, nothing, redirect, redirect_limit, redirect_method, forwardheaders) do method, uri, headers, body
        reqclient = @something(client, getclient(ClientSettings(scheme(uri), host(uri), getport(uri); ssl_alpn_list="http/1.1", kw...)))::Client
        path = resource(uri)
        with_request(reqclient, method, path, headers, body, nothing, false, (username !== nothing && password !== nothing) ? "$username:$password" : userinfo(uri), bearer, modifier, false, cookies, cookiejar, verbose) do req
            ws_host = header(req, "host", String(host(uri)))
            ws = WebSocket(ws_host, path; maxframesize=maxframesize, maxfragmentation=maxfragmentation, is_client=true)
            ws.handshake_request = req
            with_connection(reqclient) do conn
                stream = _open_stream(conn, req, false, 0)
                resp = startread(stream)
                ws.handshake_response = resp
                if resp.status != 101
                    # Not a WebSocket upgrade; finish the stream and return ws
                    # so with_redirect can follow 3xx redirects via getresponse(ws)
                    try; closeread(stream); catch; end
                    return ws
                end
                if !isupgrade(resp)
                    try; closeread(stream); catch; end
                    AwsHTTP.http_connection_close(conn)
                    handshakeerror()
                end
                accept = getheader(resp.headers, "sec-websocket-accept")
                if accept === nothing || accept != expected_accept
                    try; closeread(stream); catch; end
                    AwsHTTP.http_connection_close(conn)
                    handshakeerror()
                end
                # Wait for the H1 stream to complete (fires with ERROR_HTTP_SWITCHED_PROTOCOLS)
                try
                    wait(stream.fut)
                catch
                    # Expected: ERROR_HTTP_SWITCHED_PROTOCOLS
                end
                # Swap the H1Connection handler with our WsChannelHandler
                h1conn = stream.aws_stream.owning_connection
                slot = h1conn.slot
                _create_ws_handler!(ws, slot, true)
                verbose > 0 && @info "$(ws.id): WebSocket opened"
                # Run WebSocket session
                try
                    f(ws)
                catch e
                    if !isok(e)
                        suppress_close_error || @error "$(ws.id): error" exception=(e, catch_backtrace())
                    end
                    if !isclosed(ws)
                        if e isa WebSocketError && e.message isa CloseFrameBody
                            close(ws, e.message)
                        else
                            close(ws, CloseFrameBody(1008, "Unexpected client websocket error"))
                        end
                    end
                    if !isok(e)
                        rethrow()
                    end
                finally
                    if !isclosed(ws)
                        close(ws, CloseFrameBody(1000, ""))
                    end
                    AwsHTTP.http_connection_close(conn)
                end
            end
            return ws
        end
    end
    # After redirect loop: verify we actually got a 101 upgrade
    resp = ws.handshake_response
    if resp === nothing || resp.status != 101
        throw(WebSocketError(CloseFrameBody(1002, "Websocket handshake failed: status $(resp === nothing ? 0 : resp.status)")))
    end
    return ws
end

# ─── Server-side upgrade ───

# Given a WebSocket request, return the 101 response
function websocket_upgrade_handler(req::Request)
    if !isupgrade(req)
        return Response(400, ["content-type" => "text/plain"], "websocket upgrade required")
    end
    if !hasheader(req, "Sec-WebSocket-Version", "13")
        return Response(400, ["content-type" => "text/plain"], "unsupported websocket version")
    end
    key = getheader(req.headers, "sec-websocket-key")
    if key === nothing || isempty(key)
        return Response(400, ["content-type" => "text/plain"], "missing websocket key")
    end
    accept_key = AwsHTTP.ws_compute_accept_key(key)
    resp = Response(101, [
        "upgrade" => "websocket",
        "connection" => "upgrade",
        "sec-websocket-accept" => accept_key,
    ], nothing)
    return resp
end

function websocket_upgrade_function(f; suppress_close_error::Bool=false, maxframesize::Integer=typemax(Int), maxfragmentation::Integer=DEFAULT_MAX_FRAG, done=nothing)
    function websocket_upgrade(stream::Stream)
        resp = isdefined(stream, :response) ? stream.response : nothing
        if resp === nothing || resp.status != 101
            done !== nothing && notify(done, CapturedException(ArgumentError("websocket upgrade not accepted"), Base.backtrace()))
            return
        end
        req = stream.request
        ws = WebSocket(header(req, "host", ""), req.path; maxframesize=maxframesize, maxfragmentation=maxfragmentation, is_client=false)
        ws.handshake_request = req
        ws.handshake_response = resp
        # Get the H1Connection's channel slot and swap in our WebSocket handler
        h1conn = stream.aws_stream.owning_connection
        slot = h1conn.slot
        _create_ws_handler!(ws, slot, false)
        errormonitor(Threads.@spawn begin
            err = nothing
            try
                f(ws)
            catch e
                if !isok(e)
                    err = e
                    suppress_close_error || @error "$(ws.id): error" exception=(e, catch_backtrace())
                end
                if !isclosed(ws)
                    if e isa WebSocketError && e.message isa CloseFrameBody
                        close(ws, e.message)
                    elseif isok(e)
                        close(ws, CloseFrameBody(1000, ""))
                    else
                        close(ws, CloseFrameBody(1011, "Unexpected server websocket error"))
                    end
                end
                if err !== nothing
                    done !== nothing && notify(done, CapturedException(e, catch_backtrace()))
                end
                if !isok(e)
                    rethrow()
                end
            finally
                if err === nothing
                    if !isclosed(ws)
                        close(ws, CloseFrameBody(1000, ""))
                    end
                    done !== nothing && notify(done, nothing)
                end
                AwsHTTP.http_connection_close(h1conn)
            end
        end)
        return
    end
end

function _upgrade(f::Function, stream::Stream; suppress_close_error::Bool=false, maxframesize::Integer=typemax(Int), maxfragmentation::Integer=DEFAULT_MAX_FRAG)
    isupgrade(stream) || handshakeerror()
    hasheader(stream.request, "Sec-WebSocket-Version", "13") || handshakeerror()
    key = getheader(stream.request.headers, "sec-websocket-key")
    (key === nothing || isempty(key)) && handshakeerror()
    stream.response_started && error("response already started")
    done = Future{Nothing}()
    stream.on_complete = websocket_upgrade_function(f; suppress_close_error=suppress_close_error, maxframesize=maxframesize, maxfragmentation=maxfragmentation, done=done)
    stream.response = websocket_upgrade_handler(stream.request)
    startwrite(stream)
    closewrite(stream)
    wait(done)
    return
end

upgrade(f::Function, stream::Stream; kw...) = _upgrade(f, stream; kw...)
upgrade(stream::Stream, f::Function; kw...) = _upgrade(f, stream; kw...)

serve!(f, host="127.0.0.1", port=8080; suppress_close_error::Bool=false, maxframesize::Integer=typemax(Int), maxfragmentation::Integer=DEFAULT_MAX_FRAG, kw...) =
    HTTP.serve!(websocket_upgrade_handler, host, port; on_stream_complete=websocket_upgrade_function(f; suppress_close_error=suppress_close_error, maxframesize=maxframesize, maxfragmentation=maxfragmentation), kw...)

listen!(f, host="127.0.0.1", port=8080; kw...) = serve!(f, host, port; kw...)

function listen(f, host="127.0.0.1", port=8080; kw...)
    server = listen!(f, host, port; kw...)
    wait(server)
    return server
end

end # module
